import {
  BedDouble,
  BookOpen,
  Briefcase,
  CalendarCheck,
  CircleDot,
  Coffee,
  Code2,
  Dumbbell,
  Gamepad2,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Languages,
  Lightbulb,
  ListChecks,
  MessageCircle,
  MonitorPlay,
  Moon,
  ShoppingBag,
  Sunrise,
  Trophy,
  UsersRound,
  Video,
  type LucideIcon,
} from "lucide-react";

export const taskIconNames = [
  "sunrise",
  "focus",
  "dumbbell",
  "briefcase",
  "calendar-check",
  "book-open",
  "graduation-cap",
  "languages",
  "code-2",
  "lightbulb",
  "message-circle",
  "users-round",
  "coffee",
  "laptop",
  "monitor-play",
  "gamepad-2",
  "house",
  "shopping-bag",
  "trophy",
  "circle-dot",
  "heart-pulse",
  "heart",
  "video",
  "bed-double",
  "moon",
] as const;

export type TaskIconName = (typeof taskIconNames)[number];

const icons: Record<TaskIconName, LucideIcon> = {
  sunrise: Sunrise,
  focus: ListChecks,
  dumbbell: Dumbbell,
  briefcase: Briefcase,
  "calendar-check": CalendarCheck,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  languages: Languages,
  "code-2": Code2,
  lightbulb: Lightbulb,
  "message-circle": MessageCircle,
  "users-round": UsersRound,
  coffee: Coffee,
  laptop: Laptop,
  "monitor-play": MonitorPlay,
  "gamepad-2": Gamepad2,
  house: House,
  "shopping-bag": ShoppingBag,
  trophy: Trophy,
  "circle-dot": CircleDot,
  "heart-pulse": HeartPulse,
  heart: Heart,
  video: Video,
  "bed-double": BedDouble,
  moon: Moon,
};

export function taskIcon(name: TaskIconName | undefined) {
  return name ? icons[name] : undefined;
}
